name: Build and Push Docker Image for Frontend

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build_and_push:
    runs-on: ubuntu-frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Frontend Docker Image
        run: |
          docker build -t igrowker/pawsome:${{ github.sha }} -t igrowker/pawsome:frontend ./i004-pawsome-front/Dockerfile

      - name: Push Frontend Docker Image
        run: |
          docker push igrowker/pawsome:${{ github.sha }}
          docker push igrowker/pawsome:frontend
